
#define StrPlainImage			"PlainImage"
#define StrCipherImage			"CipherImage"
#define StrPlainHist			"PlainHist"
#define StrCipherHist			"CipherHist"
#define StrPlainHorz			"PlainHorz"
#define StrPlainVert			"PlainVert"
#define StrPlainDiag			"PlainDiag"
#define StrCipherHorz			"CipherHorz"
#define StrCipherVert			"CipherVert"
#define StrCipherDiag			"CipherDiag"
